#!/bin/bash
# A script to generate a AOSC OS stage1 (pre-package manager) system.

# Help message.
_help_message() {
    printf "\
Kaboom: Bootstrap AOSC OS stage1 (pre-package manager) system from scratch.

Usage:

	kaboom [ARCH]

	- [ARCH]: Architecture to bootstrap AOSC OS for.

"
}

# Define environmental definitions.
export _TOPDIR="$PWD"
export _CONFDIR="$_TOPDIR"/etc
export _LIBDIR="$_TOPDIR"/lib
export _PROCDIR="$_TOPDIR"/proc
export _STAGE0="$_TOPDIR"/stage0

# Output formatters.
abwarn() { echo -e "[\e[33mWARN\e[0m]: \e[1m$*\e[0m"; }
aberr()  { echo -e "[\e[31mERROR\e[0m]: \e[1m$*\e[0m"; exit 1; }
abinfo() { echo -e "[\e[96mINFO\e[0m]: \e[1m$*\e[0m"; }

# Test if essential variables are set.
if [ -z "${1}" ]; then
    echo -e '[!!!] Please specify an architecture to bootstrap AOSC OS for!'
    _help_message
    exit 1
fi

# Pass $1 to $KABOOM_ARCH, used by other scripts.
export KABOOM_ARCH="${1}"

# Check if KABOOM_ARCH is valid.
if ! grep -qFx "$KABOOM_ARCH" data/supported-arch; then
    aberr 'The $KABOOM_ARCH specified is not yet supported by Kaboom. Please consider adapting Kaboom to this architecture.'
fi

# Load libraries.
for bashlib in "$_LIBDIR"/*.bash; do
    abinfo "Loading library: $bashlib ..."
    source "$bashlib"
done

# Execute main loop.
for proc in "$_PROCDIR"/*.bash; do
    abinfo "Executing procedural loop: $proc ..."
    source "$proc"
done
